/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Command: npx gltfjsx@6.5.3 public/models/common_construction.glb -o src/components/three/landmark/CommonConstructionModel.jsx --keepnames
  Adapted: 40곳 Clone 배치 + WORK_COMMON 건설 모션. 노드명 점(.) 때문에 메시 JSX 나열 대신 scene clone.
*/

import { useEffect, useLayoutEffect, useMemo } from 'react';
import { AnimationMixer, LoopRepeat } from 'three';
import { clone as cloneSkeleton } from 'three/examples/jsm/utils/SkeletonUtils.js';
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import { skipRaycast } from './landmarkGlbMap';

export const COMMON_CONSTRUCTION_GLB = '/models/common_construction.glb';

export function CommonConstructionModel({
  playWork = true,
  workSpeed = 0.85,
  ...props
}) {
  const { scene, animations } = useGLTF(COMMON_CONSTRUCTION_GLB);
  const clone = useMemo(() => cloneSkeleton(scene), [scene]);
  const mixer = useMemo(() => new AnimationMixer(clone), [clone]);
  const clip = useMemo(
    () => animations.find((item) => item.name === 'WORK_COMMON') ?? animations[0],
    [animations],
  );

  useLayoutEffect(() => {
    const completed = clone.getObjectByName('COMPLETED_construction_common');
    if (completed) completed.visible = false;
    clone.traverse((obj) => {
      if (!obj.isMesh) return;
      obj.renderOrder = 2;
      obj.frustumCulled = false;
      obj.raycast = skipRaycast;
    });
  }, [clone]);

  useEffect(() => {
    if (!clip) return undefined;
    const action = mixer.clipAction(clip);
    action.setLoop(LoopRepeat, Infinity);
    action.clampWhenFinished = false;
    action.enabled = true;
    action.timeScale = workSpeed;
    if (playWork) {
      action.paused = false;
      action.play();
    } else {
      action.paused = true;
    }
    return () => {
      action.stop();
    };
  }, [clip, mixer, playWork, workSpeed]);

  useFrame((_, delta) => {
    if (playWork) mixer.update(delta);
  });

  return (
    <group {...props} dispose={null}>
      <primitive object={clone} />
    </group>
  );
}

useGLTF.preload(COMMON_CONSTRUCTION_GLB);
